# 1. Merging Raw Data from Evolutionary Simulations

**Imports**

In [1]:
import numpy as np

import sympy as sym

import itertools

import pandas as pd

import glob

In [2]:
from operator import itemgetter

In [3]:
import matplotlib.pyplot as plt

import matplotlib

from mpl_toolkits.axes_grid1 import make_axes_locatable

In [4]:
import tqdm

## Preparation to Read Files

In [5]:
cs = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

In [6]:
names1 = [f"p_{i}" for i in range(1, 3)] + ["t", "cooperation"]
names2 = [f"p_{i}" for i in range(1, 5)] + ["t", "cooperation"]
names3 = [f"p_{i}" for i in range(1, 9)] + ["t", "cooperation"]

In [7]:
def frequencies(df, max_steps=10**7):
    frequencies = []
    previous = 0
    for value in df["t"][1:]:
        frequencies.append(value - previous)
        previous = value
    frequencies.append(max_steps - previous)

    df["frequencies"] = np.array(frequencies)
    df["frequencies norm"] = np.array(frequencies) / max_steps

    return df

We want to assess how many resident strategies are partner strategies in our simulation. For a resident strategy to be classified as a partner, it must satisfy all inequalities in the respective definition of partner strategies and cooperate
with a probability of at least 95\% after full cooperation.

In [8]:
def one_bit_condition_one(p1, p2, c, b):
    return p2 < 1 - c / b


def one_bit_condition_two(p1, p2, c, b):
    return p1 > 0.95


def is_partner_one_bit(p1, p2, c, b):
    return (one_bit_condition_one(p1, p2, c, 1)) and (
        one_bit_condition_two(p1, p2, c, 1)
    )

In [9]:
def two_bit_condition_one(p1, p2, p3, p4, c, b):
    return p4 < (1 - c / b)


def two_bit_condition_two(p1, p2, p3, p4, c, b):
    return p2 + p3 < (2 - c / b)


def two_bit_condition_three(p1, p2, p3, p4, c, b):
    return p1 > 0.95


def is_partner_two_bits(p1, p2, p3, p4, c, b):
    return (
        (two_bit_condition_one(p1, p2, p3, p4, c, 1))
        and two_bit_condition_two(p1, p2, p3, p4, c, 1)
        and two_bit_condition_three(p1, p2, p3, p4, c, 1)
    )

In [10]:
def three_bit_condition_one(p1, p2, p3, p4, p5, p6, p7, p8, c, b):
    return p8 < (1 - c / b)


def three_bit_condition_two(p1, p2, p3, p4, p5, p6, p7, p8, c, b):
    return p3 + p6 < (2 - c / b)


def three_bit_condition_three(p1, p2, p3, p4, p5, p6, p7, p8, c, b):
    return p2 + p3 + p5 < (3 - c / b)


def three_bit_condition_four(p1, p2, p3, p4, p5, p6, p7, p8, c, b):
    return p4 + p6 + p7 < (3 - 2 * c / b)


def three_bit_condition_five(p1, p2, p3, p4, p5, p6, p7, p8, c, b):
    return p2 + p4 + p5 + p7 < (4 - 2 * c / b)


def three_bit_condition_six(p1, p2, p3, p4, p5, p6, p7, p8, c, b):
    return p1 > 0.95


def is_partner_three_bits(p1, p2, p3, p4, p5, p6, p7, p8, c, b):
    return (
        (three_bit_condition_one(p1, p2, p3, p4, p5, p6, p7, p8, c, 1))
        and (three_bit_condition_two(p1, p2, p3, p4, p5, p6, p7, p8, c, 1))
        and (three_bit_condition_three(p1, p2, p3, p4, p5, p6, p7, p8, c, 1))
        and (three_bit_condition_four(p1, p2, p3, p4, p5, p6, p7, p8, c, 1))
        and (three_bit_condition_five(p1, p2, p3, p4, p5, p6, p7, p8, c, 1))
        and (three_bit_condition_six(p1, p2, p3, p4, p5, p6, p7, p8, c, 1))
    )

#  Reactive-1

In [11]:
files = glob.glob(f"../data/matlab_data/bits_2_beta_*_seed_1_*.csv")

files += glob.glob(f"../data/beta_2/bits_2_beta_*_seed_1_*.csv")

In [12]:
one_bits = []

for file in files:
    c = float(file.split("c_")[1].split(".csv")[0])

    beta = float(file.split("_beta_")[1].split("_")[0])

    df = pd.read_csv(file, names=names1)

    df = df.drop_duplicates()

    df["c"] = c

    df["beta"] = beta

    df = frequencies(df, 10**7)

    one_bits.append(df)

In [13]:
one_bits = pd.concat(one_bits)

In [14]:
one_bits["beta"].unique()

array([10. ,  1. ,  0.1,  2. ])

In [15]:
ispartner = []

for i, row in tqdm.tqdm(one_bits.iterrows()):
    condition = is_partner_one_bit(row["p_1"], row["p_2"], row["c"], 1)

    ispartner.append(condition)

1668615it [01:01, 27199.07it/s]


In [16]:
one_bits["isPartner"] = ispartner

In [17]:
one_bits.to_csv("../prc_data/evolution_over_c_and_beta_reactive_one.csv")

# Reactive-1

In [35]:
files = glob.glob(f"../data/matlab_data/bits_4_beta_0.1_seed_1_*.csv")

files += glob.glob(f"../data/matlab_data/bits_4_beta_1_seed_1_*.csv")

files += glob.glob(f"../data/beta_2/bits_4_beta_2_seed_1_*.csv")

two_bits = []

for file in files:
    c = float(file.split("c_")[1].split(".csv")[0])

    beta = float(file.split("_beta_")[1].split("_")[0])

    df = pd.read_csv(file, names=names2)

    df = df.drop_duplicates()

    df["c"] = c

    df["beta"] = beta

    df = frequencies(df, 10**7)

    two_bits.append(df)

In [36]:
files = glob.glob("../data/long/bits_4_beta_10_seed_1_c_*.csv")

for file in files:
    c = float(file.split("c_")[1].split(".csv")[0])

    beta = float(file.split("beta_")[1].split("_")[0])

    df = pd.read_csv(file, names=names2)

    df = df.drop_duplicates()

    df["c"] = c

    df["beta"] = beta

    df = frequencies(df, 10**8)

    two_bits.append(df)

In [37]:
two_bits = pd.concat(two_bits)

In [38]:
two_bits["beta"].unique()

array([ 0.1,  1. ,  2. , 10. ])

In [39]:
ispartner = []

for i, row in tqdm.tqdm(two_bits.iterrows()):
    condition = is_partner_two_bits(
        row["p_1"], row["p_2"], row["p_3"], row["p_4"], row["c"], 1
    )

    ispartner.append(condition)

1913480it [01:14, 25775.21it/s]


In [40]:
two_bits["isPartner"] = ispartner

In [41]:
two_bits.to_csv("../prc_data/evolution_over_c_and_beta_reactive_two.csv")

## Reactive-2 Counting

In [53]:
files = glob.glob(f"../data/counting/bits_4_beta_0.1_seed_1_c_*.csv")
files += glob.glob(f"../data/counting/bits_4_beta_1_seed_1_c_*.csv")
files += glob.glob(f"../data/counting/bits_4_beta_10_seed_1_c_*.csv")
files += glob.glob(f"../data/counting/bits_4_beta_2_seed_1_c_*.csv")

In [54]:
counting_two_bits = []

for file in files:
    c = float(file.split("c_")[1].split(".csv")[0])

    beta = float(file.split("beta_")[1].split("_")[0])

    df = pd.read_csv(file, names=names2)

    df = df.drop_duplicates()

    df["c"] = c

    df["beta"] = beta

    df = frequencies(df, 10**7)

    counting_two_bits.append(df)

In [55]:
counting_two_bits = pd.concat(counting_two_bits)

In [56]:
ispartner = []

for i, row in tqdm.tqdm(counting_two_bits.iterrows()):
    condition = is_partner_two_bits(
        row["p_1"], row["p_2"], row["p_3"], row["p_4"], row["c"], 1
    )

    ispartner.append(condition)

1886774it [01:14, 25240.79it/s]


In [57]:
counting_two_bits["isPartner"] = ispartner

In [58]:
counting_two_bits["beta"].unique()

array([ 0.1,  1. , 10. ,  2. ])

In [59]:
counting_two_bits.to_csv(
    "../prc_data/evolution_over_c_and_beta_reactive_counting_two.csv"
)

# Reactive-3

In [60]:
files = glob.glob(f"../data/matlab_data/bits_8_beta_0.1_seed_1_*.csv")
files += glob.glob(f"../data/matlab_data/bits_8_beta_1_seed_1_*.csv")
files += glob.glob(f"../data/beta_2/bits_8_beta_2_seed_1_*.csv")

In [61]:
three_bits = []

for file in files:
    c = float(file.split("c_")[1].split(".csv")[0])

    beta = float(file.split("_beta_")[1].split("_")[0])

    df = pd.read_csv(file, names=names3)

    df = df.drop_duplicates()

    df["c"] = c

    df["beta"] = beta

    df = frequencies(df, 2 * 10**7)

    three_bits.append(df)

In [62]:
files = glob.glob(f"../data/beta_2/bits_8_beta_10_seed_1_c_*.csv")

In [63]:
for file in files:
    c = float(file.split("c_")[1].split(".csv")[0])

    beta = float(file.split("_beta_")[1].split("_")[0])

    df = pd.read_csv(file, names=names3)

    df = df.drop_duplicates()

    df["c"] = c

    df["beta"] = beta

    df = frequencies(df, 40000000)

    three_bits.append(df)

In [64]:
three_bits = pd.concat(three_bits)

In [65]:
three_bits["beta"].unique()

array([ 0.1,  1. ,  2. , 10. ])

In [66]:
ispartner = []

for i, row in tqdm.tqdm(three_bits.iterrows()):
    condition = is_partner_three_bits(
        row["p_1"],
        row["p_2"],
        row["p_3"],
        row["p_4"],
        row["p_5"],
        row["p_6"],
        row["p_7"],
        row["p_8"],
        row["c"],
        1,
    )

    ispartner.append(condition)

2640162it [02:05, 21047.36it/s]


In [67]:
three_bits["isPartner"] = ispartner

In [68]:
three_bits.to_csv("../prc_data/evolution_over_c_and_beta_reactive_three.csv")

## Reactive-3 Counting

In [70]:
files = glob.glob(f"../data/counting/bits_8_beta_0.1_seed_1_c_*.csv")
files += glob.glob(f"../data/counting/bits_8_beta_1_seed_1_c_*.csv")
files += glob.glob(f"../data/counting/bits_8_beta_10_seed_1_c_*.csv")
files += glob.glob(f"../data/counting/bits_8_beta_2_seed_1_c_*.csv")

In [71]:
counting_three_bits = []

for file in files:
    c = float(file.split("c_")[1].split(".csv")[0])

    beta = float(file.split("beta_")[1].split("_")[0])

    df = pd.read_csv(file, names=names3)

    df = df.drop_duplicates()

    df["c"] = c

    df["beta"] = beta

    df = frequencies(df, 2 * 10**7)

    counting_three_bits.append(df)

In [72]:
counting_three_bits = pd.concat(counting_three_bits)

In [73]:
ispartner = []

for i, row in tqdm.tqdm(counting_three_bits.iterrows()):
    condition = is_partner_three_bits(
        row["p_1"],
        row["p_2"],
        row["p_3"],
        row["p_4"],
        row["p_5"],
        row["p_6"],
        row["p_7"],
        row["p_8"],
        row["c"],
        1,
    )

    ispartner.append(condition)

3580753it [03:00, 19822.09it/s]


In [74]:
counting_three_bits["isPartner"] = ispartner

In [75]:
counting_three_bits["beta"].unique()

array([ 0.1,  1. , 10. ,  2. ])

In [76]:
counting_three_bits.to_csv(
    "../prc_data/evolution_over_c_and_beta_reactive_counting_three.csv"
)

# Results with different seeds

In [8]:
import os

In [9]:
import glob

In [10]:
dfs = []

for sdim, type_, max_step, name in zip(
    [2, 4, 8],
    ["one", "two", "three"],
    [10**7, 10**7, 2 * 10**7],
    [names1, names2, names3],
):
    for seed in range(11, 21):
        file = f"../data/evolution_over_seeds/bits_{sdim}_beta_1_seed_{seed}_c_0.5.csv"

        df = pd.read_csv(file, names=name)

        df = df.drop_duplicates()

        df["type"] = type_
        df["seed"] = seed

        df = frequencies(df, max_step)

        dfs.append(df)

In [11]:
df = pd.concat(dfs)

In [12]:
df1 = pd.read_csv("../prc_data/evolution_over_seeds_reactive.csv", index_col=0)

In [13]:
df1['seed'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
df['seed'].unique()

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
merged = pd.concat([df, df1])

In [16]:
merged = merged.sort_values(['type', 'seed'])

In [ ]:
merged.to_csv("../prc_data/evolution_over_seeds_reactive_new.csv")

## Results for Counting Strategies

In [ ]:
dfs = []

for sdim, type_, max_step, name in zip(
    [4, 8],
    ["counting-two", "counting-three"],
    [10**7, 2 * 10**7],
    [names2, names3],
):
    for seed in range(1, 21):
        file = f"../data/counting/bits_{sdim}_beta_1_seed_{seed}_c_0.5.csv"

        df = pd.read_csv(file, names=name)

        df = df.drop_duplicates()

        df["type"] = type_
        df["seed"] = seed

        df = frequencies(df, max_step)

        dfs.append(df)

In [ ]:
df = pd.concat(dfs)

In [ ]:
df.to_csv("../prc_data/evolution_over_seeds_reactive_counting.csv")