In [25]:
import sys  
sys.path.insert(0, '../src/')

import main

import itertools

import numpy as np

In [8]:
def calculate_M_memory_two(player, coplayer):

    (
        p1,
        p2,
        p3,
        p4,
        p5,
        p6,
        p7,
        p8,
        p9,
        p10,
        p11,
        p12,
        p13,
        p14,
        p15,
        p16,
    ) = player
    (
        q1,
        q2,
        q3,
        q4,
        q5,
        q6,
        q7,
        q8,
        q9,
        q10,
        q11,
        q12,
        q13,
        q14,
        q15,
        q16,
    ) = coplayer

    M = np.zeros((16, 16))

    col, row = 0, 0

    for p, q in [[p1, q1], [p2, q3], [p3, q2], [p4, q4]]:
        for i, combo in enumerate(
            [(p * q), ((1 - q) * p), ((1 - p) * q), ((1 - p) * (1 - q))]
        ):

            M[row, col + i] = combo

        col += 4
        row += 1

    col = 0
    for p, q in [[p5, q9], [p6, q11], [p7, q10], [p8, q12]]:
        for i, combo in enumerate(
            [(p * q), ((1 - q) * p), ((1 - p) * q), ((1 - p) * (1 - q))]
        ):

            M[row, col + i] = combo

        col += 4
        row += 1

    col = 0
    for p, q in [[p9, q5], [p10, q7], [p11, q6], [p12, q8]]:
        for i, combo in enumerate(
            [(p * q), ((1 - q) * p), ((1 - p) * q), ((1 - p) * (1 - q))]
        ):

            M[row, col + i] = combo

        col += 4
        row += 1

    col = 0
    for p, q in [[p13, q13], [p14, q15], [p15, q14], [p16, q16]]:
        for i, combo in enumerate(
            [(p * q), ((1 - q) * p), ((1 - p) * q), ((1 - p) * (1 - q))]
        ):

            M[row, col + i] = combo

        col += 4
        row += 1

    return M


def calculate_M(player, opponent):
    """
    Returns a Markov transition matrix for a game of memory one strategies.
    """
    return np.array(
        [
            [
                player[0] * opponent[0],
                player[0] * (1 - opponent[0]),
                (1 - player[0]) * opponent[0],
                (1 - player[0]) * (1 - opponent[0]),
            ],
            [
                player[1] * opponent[2],
                player[1] * (1 - opponent[2]),
                (1 - player[1]) * opponent[2],
                (1 - player[1]) * (1 - opponent[2]),
            ],
            [
                player[2] * opponent[1],
                player[2] * (1 - opponent[1]),
                (1 - player[2]) * opponent[1],
                (1 - player[2]) * (1 - opponent[1]),
            ],
            [
                player[3] * opponent[3],
                player[3] * (1 - opponent[3]),
                (1 - player[3]) * opponent[3],
                (1 - player[3]) * (1 - opponent[3]),
            ],
        ]
    )


In [17]:
mem_one_strategies = list(itertools.product([0, 1], repeat=4))

In [115]:
import math

In [122]:
player = mem_one_strategies[2]

for strategy in mem_one_strategies:
    M = calculate_M_memory_two(player * 4, strategy * 4)
    
    ss = main.invariant_distribution(M)
    
    oooo = ss * (strategy * 4)
    
    proxy = [sum(np.array([oooo[i] for i in np.arange(j, 16, 4)])) for j in range(4)]
    
#     print(proxy, strategy)
    
    print(main.invariant_distribution(calculate_M(player, proxy)),
         [sum([ss[i] for i in np.arange(j, 16, 4)]) for j in range(4)])

[0. 0. 0. 1.] [0.0, 0.0, 0.0, 1.0]
[-0.   0.2  0.2  0.6] [0.0, 0.3333333333333333, 0.3333333333333335, 0.3333333333333333]
[0. 0. 0. 1.] [0.0, 0.5, 0.5, 0.0]
[0. 0. 0. 1.] [0.0, 0.5, 0.5, 0.0]
[0. 0. 0. 1.] [0.0, 0.0, 0.0, 1.0]
[-0.   0.2  0.2  0.6] [0.3333333333333333, 0.0, 0.3333333333333335, 0.3333333333333333]
[0. 0. 0. 1.] [0.0, 0.0, 0.0, 1.0]
[0.   0.25 0.25 0.5 ] [0.3333333333333333, 0.0, 0.3333333333333335, 0.3333333333333333]
[0. 0. 0. 1.] [0.0, 0.0, 0.0, 1.0]
[-0.   0.2  0.2  0.6] [0.0, 0.3333333333333333, 0.3333333333333335, 0.3333333333333333]
[0. 0. 0. 1.] [0.0, 0.5, 0.5, 0.0]
[0. 0. 0. 1.] [0.0, 0.5, 0.5, 0.0]
[0. 0. 0. 1.] [0.5, 0.0, 0.5, 0.0]
[0. 0. 0. 1.] [0.5, 0.0, 0.5, 0.0]
[0. 0. 0. 1.] [0.5, 0.0, 0.5, 0.0]
[0. 0. 0. 1.] [0.5, 0.0, 0.5, 0.0]


In [114]:
int(0.9)

0

In [16]:
2 ** 8

256

In [106]:
ss

array([0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0. ,
       0. , 0. , 0. ])

In [108]:
strategy * 4

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [95]:
proxy, strategy

([0.0, 0.0, 1.0, 0.0], (1, 1, 1, 1))

In [96]:
ss

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [85]:
ss

array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. ,
       0. , 0.5, 0. ])

In [78]:
ss

array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. ,
       0. , 0.5, 0. ])

In [57]:
M = calculate_M_memory_two(mem_one_strategies[-1] * 4, mem_one_strategies[1] * 4)

In [58]:
ss = main.invariant_distribution(M)

In [59]:
oooo = ss * (mem_one_strategies[1] * 4)

In [60]:
[sum([ss[i] for i in np.arange(j, 16, 4)]) for j in range(4)]

[0.0, 1.0, 0.0, 0.0]

In [61]:
[sum([oooo[i] for i in np.arange(j, 16, 4)]) for j in range(4)]

[0.0, 0.0, 0.0, 0.0]

In [62]:
mem_one_strategies[1]

(0, 0, 0, 1)

In [65]:
main.invariant_distribution(calculate_M(mem_one_strategies[-1], mem_one_strategies[0]))

array([0., 1., 0., 0.])