In [4]:
import sympy as sym

import numpy as np

In [65]:
def calculate_M(player, opponent):
    """
    Returns a Markov transition matrix for a game of memory one strategies.
    """
    return sym.Matrix(
        [
            [
                player[0] * opponent[0],
                player[0] * (1 - opponent[0]),
                (1 - player[0]) * opponent[0],
                (1 - player[0]) * (1 - opponent[0]),
            ],
            [
                player[1] * opponent[2],
                player[1] * (1 - opponent[2]),
                (1 - player[1]) * opponent[2],
                (1 - player[1]) * (1 - opponent[2]),
            ],
            [
                player[2] * opponent[1],
                player[2] * (1 - opponent[1]),
                (1 - player[2]) * opponent[1],
                (1 - player[2]) * (1 - opponent[1]),
            ],
            [
                player[3] * opponent[3],
                player[3] * (1 - opponent[3]),
                (1 - player[3]) * opponent[3],
                (1 - player[3]) * (1 - opponent[3]),
            ],
        ]
    )

In [66]:
def invariant_distribution_analytically(M):
    size = M.shape[1]
    pi = sym.symbols(f"b_1:{size + 1}")
    ss = sym.solve(
        [sum(pi) - 1]
        + [a - b for a, b in zip(M.transpose() * sym.Matrix(pi), pi)],
        pi,
    )

    v_vector = sym.Matrix(
        [
            [ss[p] for p in pi],
        ]
    )

    return v_vector

In [42]:
def invariant_distribution(M):

    eigenvalues, eigenvectors = np.linalg.eig(M.T)
    eigenvectors_one = eigenvectors[:, np.argmax(eigenvalues)]

    stationary = eigenvectors_one / eigenvectors_one.sum()

    return stationary.real

In [43]:
p1, p2, p3, p4 = sym.symbols("p1, p2, p3, p4")
q1, q2, q3, q4 = sym.symbols("q1, q2, q3, q4")

In [68]:
M = calculate_M((p1, p2, p3, p4), (q1, q2, q3, q4))

In [79]:
M = M.subs({p1: 1, p2:0, p3:1, p4:0, q1:1, q2:0, q3:1, q4:0})

In [83]:
M = np.array(M, dtype=float)

In [84]:
eigenvalues, eigenvectors = np.linalg.eig(M.T)

In [90]:
eigenvectors_one = eigenvectors[:, 2]

stationary = eigenvectors_one / eigenvectors_one.sum()

stationary.real

array([1., 0., 0., 0.])

In [69]:
ss = invariant_distribution_analytically(M)

In [72]:
ss[0].subs({p1: 1, p2:0, p3:1, p4:0, q1:1})

1

In [64]:
M =  calculate_M((1, 0, 1, 0), (1, 0, 1, 0))

ss = invariant_distribution(M)

In [61]:
M 

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [62]:
ss

array([0. , 0.5, 0.5, 0. ])

In [63]:
ss @ Sy, ss @ Sx

(0.5, 0.5)

In [187]:
R = 3
S = 0
T = 5
P = 1

Sx = np.array([R, S, T, P])
Sy = np.array([R, T, S, P])

In [188]:
expr1 = ((T - R) / (R - S)) * p3 <= 1 - p2

expr2 = ((T - R) / (R - P)) * p4 <= 1 - p2

In [189]:
expr2.subs({p4:0}).simplify()

p2 <= 1

In [202]:
expr1.subs({p3:0.758}).simplify()

p2 <= 0.494666666666667

In [198]:
strategy = [1, 0, 0.5, 0]

coplayer = [1, 0, 0.5, 0]

In [199]:
s = [ss[i].subs({p1:strategy[0],
            p2:strategy[1],
            p3:strategy[2],
            p4:strategy[3],
            q1:coplayer[0],
            q2:coplayer[1],
            q3:coplayer[2],
            q4:coplayer[3]}) for i in range(4)]

In [200]:
s

[1.00000000000000, 0, 0, nan]

In [201]:
s @ Sx

nan

In [194]:
s @ Sy

0.999999999999992

In [6]:
R, S, T, P = 0.6, 0, 1, 0.3

Matrix([
[p1*q1, p1*(1 - q1), q1*(1 - p1), (1 - p1)*(1 - q1)],
[p2*q3, p2*(1 - q3), q3*(1 - p2), (1 - p2)*(1 - q3)],
[p3*q2, p3*(1 - q2), q2*(1 - p3), (1 - p3)*(1 - q2)],
[p4*q4, p4*(1 - q4), q4*(1 - p4), (1 - p4)*(1 - q4)]])