In [1]:
import sympy as sym

In [2]:
from importlib.machinery import SourceFileLoader

main = SourceFileLoader(
    "main", "../src/main.py"
).load_module()

from main import *

In [3]:
import itertools

In [4]:
pure = list(itertools.product([0, 1], repeat=4))

In [5]:
A1 = [1, 0, 0, 0]
A2 = [1, 0, 1, 0]
A3 = [1, 1, 0, 0]
A4 = [1, 1, 1, 0]

In [6]:
b, c = sym.symbols("b, c")

payoffs = np.array([2 - 1, -1, 2, 0] * 4)

In [7]:
payoffs

array([ 1, -1,  2,  0,  1, -1,  2,  0,  1, -1,  2,  0,  1, -1,  2,  0])

In [8]:
def calculate_M(player, opponent):
    """
    Returns a Markov transition matrix for a game of memory one strategies.
    """
    return np.array(
        [
            [
                player[0] * opponent[0],
                player[0] * (1 - opponent[0]),
                (1 - player[0]) * opponent[0],
                (1 - player[0]) * (1 - opponent[0]),
            ],
            [
                player[1] * opponent[2],
                player[1] * (1 - opponent[2]),
                (1 - player[1]) * opponent[2],
                (1 - player[1]) * (1 - opponent[2]),
            ],
            [
                player[2] * opponent[1],
                player[2] * (1 - opponent[1]),
                (1 - player[2]) * opponent[1],
                (1 - player[2]) * (1 - opponent[1]),
            ],
            [
                player[3] * opponent[3],
                player[3] * (1 - opponent[3]),
                (1 - player[3]) * opponent[3],
                (1 - player[3]) * (1 - opponent[3]),
            ],
        ]
    )

In [9]:
M = calculate_M([1, 0, 1, 0],
                [1, 0, 1, 0])
M

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [10]:
invariant_distribution(M) #@ np.array([2, -1, 3, 0])

array([0. , 0.5, 0.5, 0. ])

In [11]:
import sympy as sym

In [12]:
import itertools

In [13]:
import tqdm

In [14]:
pis = list(sym.symbols('p:4'))

c, b = sym.symbols("c, b")

In [15]:
payoffs = np.array([b - c, -c, b, 0] * 16)
cpayoffs = np.array([b - c, b, -c, 0] * 16)

In [16]:
64 / 4

16.0

In [17]:
# # alld = np.array([0 for _ in range(8)])

# pis[0], pis[-1] = 1, 1

In [18]:
# len(alld), len(pis)

In [19]:
s = list(itertools.product([0, 1], repeat=8))

In [20]:
to_check = []

for i in s:
    if i[0] == 1 and i[-1] == 0:
        to_check.append(i)

In [21]:
ov_scores = []

for i in tqdm.tqdm_notebook(to_check):
    scores = []
    for coplayer in s:

        M = transition_matrix(list(i), list(i),  bits=8)

        ss = invariant_distribution(M)
        
        A = ss @ payoffs

        M = transition_matrix(list(coplayer), list(i),  bits=8)

        ss = invariant_distribution(M)
        
        B = ss @ payoffs

        scores.append((A, B))
    ov_scores.append(scores)

<ipython-input-21-03a9881da6b8>:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm.tqdm_notebook(to_check):


In [22]:
sums_ = [sum(i) for i in to_check]

In [23]:
one_1 = [i for i, s in enumerate(sums_) if s == 7]

In [24]:
to_check[-1]

(1, 1, 1, 1, 1, 1, 1, 0)

In [31]:
k =[]

for i, j in ov_scores[-1]:
    A, B = float(i.subs({b:3, c:1})), float(j.subs({b:3, c:1}))
    
    if A > B or np.isclose(A, B):
        k.append(True)
    else:
        k.append(False)

In [32]:
set(k)

{True}

In [368]:
set(k)

{True}

In [357]:
# scores[0][77]

In [358]:
scores = [ov_scores[i] for i in one_1]

In [359]:
ks = []
for score in scores:
    k =[]

    for i, j in score:
        A, B = float(i.subs({b:3, c:1})), float(j.subs({b:3, c:1}))
#         print(A, B)

        if A > B: #or np.isclose(A, B): #np.isclose(A, B): # A > B or 
            k.append(True)
        else:
            k.append(False)
    ks.append(k)

In [361]:
scores

[[(0, 0),
  (0.25*b - 0.5*c, 0.5*b - 0.25*c),
  (0, 0),
  (0.333333333333333*b - 0.555555555555556*c,
   0.555555555555556*b - 0.333333333333333*c),
  (0, 0),
  (0.25*b - 0.5*c, 0.5*b - 0.25*c),
  (0, 0),
  (0.333333333333333*b - 0.555555555555555*c,
   0.555555555555555*b - 0.333333333333333*c),
  (0, 0),
  (0.3*b - 0.6*c, 0.6*b - 0.3*c),
  (0, 0),
  (0.4*b - 0.6*c, 0.6*b - 0.4*c),
  (0, 0),
  (0.3*b - 0.6*c, 0.6*b - 0.3*c),
  (0, 0),
  (0.4*b - 0.6*c, 0.6*b - 0.4*c),
  (0.166666666666667*b - 0.5*c, 0.5*b - 0.166666666666667*c),
  (0.285714285714286*b - 0.571428571428572*c,
   0.571428571428572*b - 0.285714285714286*c),
  (0, 0),
  (0.375*b - 0.625*c, 0.625*b - 0.375*c),
  (0.166666666666667*b - 0.5*c, 0.5*b - 0.166666666666667*c),
  (0.285714285714286*b - 0.571428571428571*c,
   0.571428571428571*b - 0.285714285714286*c),
  (0, 0),
  (0.375*b - 0.625*c, 0.625*b - 0.375*c),
  (0, 0),
  (0.333333333333333*b - 0.666666666666667*c,
   0.666666666666667*b - 0.333333333333333*c),
  (0, 0),

In [360]:
[set(k) for k in ks]

for i, k in zip(one_1, ks):
    print(to_check[i], set(k))

(1, 1, 1, 1, 1, 1, 1, 0) {False}


In [93]:
ks = [[i.subs({b:3, c:1}) >= j.subs({b:3, c:1}) for i, j in k] for k in scores]


In [94]:
[set(k) for k in ks]

[{False, True}, {True}, {True}, {False, True}, {True}, {True}]

In [274]:
[[j for j, i in enumerate(k) if i == False] for k in ks[:1]]

[[18, 33, 35, 51, 65, 97, 101, 146]]

In [107]:
s[248]

(1, 1, 1, 1, 1, 0, 0, 0)

In [270]:
to_check[one_1[0]], to_check[one_1[3]]

((1, 0, 0, 0, 0, 1, 1, 0), (1, 0, 0, 1, 0, 0, 1, 0))

In [272]:
sym.Matrix(ov_scores[0]).subs({b:3, c:1})

Matrix([
[               0,                     0],
[            1.25,                  0.25],
[               0,                     0],
[1.33333333333333,     0.444444444444444],
[               0,                     0],
[            1.25,                  0.25],
[               0,                     0],
[1.33333333333333,     0.444444444444444],
[               0,                     0],
[           1.625,                 0.125],
[               0,                     0],
[             1.4,                   0.6],
[               0,                     0],
[           1.625,                 0.125],
[               0,                     0],
[             1.4,                   0.6],
[               0,                     0],
[1.42857142857143,     0.285714285714286],
[               0,                     0],
[             1.5,     0.500000000000001],
[               0,                     0],
[1.42857142857143,     0.285714285714286],
[               0,                     0],
[ 

In [176]:
0.25 * (3 - 1) + 0.25 * (- 1) + 0.25 * (3)

1.0

In [132]:
s[1]

(0, 0, 0, 1)

In [122]:
sym.Matrix(ov_scores).subs({b:3, c:1})

Matrix([
[0,  1.16666666666667,   0,  1.28571428571428,   0, 1.4,                 0,               1.5, 2.0,  1.66666666666667, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0],
[0,               0.8, 1.0,               1.0,   0, 1.0,  1.14285714285714,               1.2, 2.0, 0.857142857142857, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0],
[0, 0.857142857142857,   0,               1.0, 1.0, 1.0,                 0,  1.14285714285714, 2.0,               2.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0],
[0, 0.500000000000001,   0, 0.714285714285714,   0, 0.6, 0.333333333333333, 0.833333333333334, 2.0,               2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]])

In [295]:
s[18]

(0, 0, 0, 1, 0, 0, 1, 0)

In [351]:
M = transition_matrix((1, 1, 1, 0), (0, 0, 0, 1), bits=4)

ss = invariant_distribution(M)

ss @ np.array([b - c, -c, b, 0] * 4)

0.333333333333333*b - 0.5*c

In [352]:
ss @ np.array([b - c, b, -c, 0] * 4)

0.5*b - 0.333333333333333*c

In [297]:
M

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [339]:
scores = []

player = (1, 0, 0, 0, 0, 0, 0, 0)

for i, coplayer in enumerate(s):

        M = transition_matrix(list(player), list(coplayer), bits=8)

        ss = invariant_distribution(M)

        scores.append((ss @ payoffs).subs())

In [340]:
scores

[0,
 1.25000000000000,
 0,
 1.33333333333333,
 0,
 1.25000000000000,
 0,
 1.33333333333333,
 0,
 1.62500000000000,
 0,
 1.40000000000000,
 0,
 1.62500000000000,
 0,
 1.40000000000000,
 0,
 1.42857142857143,
 0,
 1.50000000000000,
 0,
 1.42857142857143,
 0,
 1.50000000000000,
 0,
 1.85714285714286,
 0,
 1.55555555555556,
 0,
 1.85714285714286,
 0,
 1.55555555555556,
 0,
 1.25000000000000,
 0,
 1.33333333333333,
 0,
 1.25000000000000,
 0,
 1.33333333333333,
 0,
 1.62500000000000,
 0,
 1.40000000000000,
 0,
 1.62500000000000,
 0,
 1.40000000000000,
 0,
 1.42857142857143,
 0,
 1.50000000000000,
 0,
 1.42857142857143,
 0,
 1.50000000000000,
 0,
 1.85714285714286,
 0,
 1.55555555555556,
 0,
 1.85714285714286,
 0,
 1.55555555555556,
 0,
 1.62500000000000,
 0,
 1.66666666666667,
 0,
 1.62500000000000,
 0,
 1.66666666666667,
 0,
 2.00000000000000,
 0,
 1.70000000000000,
 0,
 2.00000000000000,
 0,
 1.70000000000000,
 0,
 1.66666666666667,
 0,
 1.71428571428571,
 0,
 1.66666666666667,
 0,
 1.7142

In [341]:
o_scores = []

player = (1, 0, 0, 0, 1, 0, 0, 0)

for i, coplayer in enumerate(s):

        M = transition_matrix(list(player), list(coplayer), bits=8)

        ss = invariant_distribution(M)

        o_scores.append((ss @ payoffs).subs({b:3, c:1}))

In [342]:
scores == o_scores

False

In [344]:
[scores[i] == o_scores[i] for i, _ in enumerate(scores)]

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 Fal

In [345]:
scores[1], o_scores[1]

(1.25000000000000, 1.00000000000000)

In [347]:
s[1]

(0, 0, 0, 0, 0, 0, 0, 1)